library(dplyr)
dataset <- read.csv("superstore_simple.csv")
summary(dataset)
glimpse(dataset)
dataresult <- select(dataset,c(order_id,order_date,sales))
dataresult <- select(dataset,-c(profit,sub_category))
select (dataresult,c('order_id'))
dataset_result <- filter(dataset, segment == 'Consumer' & profit > 0)
dataset_result <- filter(dataset, segment == 'Consumer' | profit > 0)
